## Numbers

Julia supports basic arithmetic with familiar syntax.

In [1]:
x = 1

1

In [2]:
x = 5*2

10

In [3]:
x += 1

11

In [4]:
x = 1.0

1.0

In [5]:
x = exp(im*π/4)

0.7071067811865476 + 0.7071067811865475im

## Vectors

You can define vectors (and matrices and multi-dimensional arrays) in Julia using several different functions:

In [6]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [7]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [8]:
fill(2.0, 3)

3-element Array{Float64,1}:
 2.0
 2.0
 2.0

In [9]:
Array(Float64, 3)

3-element Array{Float64,1}:
 6.48593e-314
 2.25027e-314
 2.23368e-314

Note that `Array` *does not* initialize the array, so before it's filled, it's full of garbage.

Indexing vectors is familiar from MATLAB, but with square brackets instead of parentheses.

In [10]:
v = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [11]:
v[1]

1

In [12]:
v[end]

3

In [13]:
v[1] = -1
v

3-element Array{Int64,1}:
 -1
  2
  3

In [14]:
v[2:end]

2-element Array{Int64,1}:
 2
 3

In [15]:
v[2:end] = 0
v

3-element Array{Int64,1}:
 -1
  0
  0

In [16]:
v[2:end] = 2:3
v

3-element Array{Int64,1}:
 -1
  2
  3

Vectors in Julia have types. Here, `v` is a vector of Int64 (64-bit integers). It can only hold numbers that can be expressed as integers.

In [17]:
v[1] = 0.5

LoadError: LoadError: InexactError()
while loading In[17], in expression starting on line 1

Fortunately, it's easy to change the type of v if we decide we want it to hold floating point numbers.

In [18]:
v = convert(Vector{Float64}, v)
v[1] = 0.5
v

3-element Array{Float64,1}:
 0.5
 2.0
 3.0

In MATLAB, assigning an array to another variable copies the array (or at least acts like it). In Julia, assigning an array to another variable creates a reference to the same array.

In [19]:
u = v
u[1] = 1
u

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [20]:
v

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

Modifying `u` modifies `v`. If we want to copy `v`, we have to do so explicitly.

In [21]:
u = copy(v)
u[1] = 2
u

3-element Array{Float64,1}:
 2.0
 2.0
 3.0

In [22]:
v

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

You can add elements to the end or beginning of a vector using `push!` and `unshift!` respectively, or add an entire vector to the end using `append!`.

In [23]:
push!(v, 4)

4-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0

In [24]:
unshift!(v, 0)

5-element Array{Float64,1}:
 0.0
 1.0
 2.0
 3.0
 4.0

In [25]:
append!(v, [5, 6])

7-element Array{Float64,1}:
 0.0
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0

Julia has no distinction between "cell arrays" and ordinary arrays. Instead, every array can hold a specific type of element. For example, we can create an array that holds `Vector{Int}`:

In [26]:
u = Array(Vector{Int}, 2)
u[1] = v
u[2] = v + 1
u

2-element Array{Array{Int64,1},1}:
 [0,1,2,3,4,5,6]
 [1,2,3,4,5,6,7]

We can also create a `Vector{Any}`, which can hold any object:

In [27]:
u = Any[1, [1, 2, 3], "hello world"]

3-element Array{Any,1}:
 1             
  [1,2,3]      
  "hello world"

## Matrices

We can concatenate two vectors to make a matrix.

In [28]:
[v v]

7x2 Array{Float64,2}:
 0.0  0.0
 1.0  1.0
 2.0  2.0
 3.0  3.0
 4.0  4.0
 5.0  5.0
 6.0  6.0

We can construct a row vector using MATLAB-style syntax.

In [29]:
A = [1 2]

1x2 Array{Int64,2}:
 1  2

Row vectors, column vectors, and row matrices are all different things.

In [30]:
B = [1, 2]

2-element Array{Int64,1}:
 1
 2

In [31]:
C = A'

2x1 Array{Int64,2}:
 1
 2

We can construct matrices using MATLAB-style syntax.

In [32]:
A = [1 2; 3 4]

2x2 Array{Int64,2}:
 1  2
 3  4

Functions beginning with `.` perform element-wise operations as in MATLAB.

In [33]:
A .* A

2x2 Array{Int64,2}:
 1   4
 9  16

In [34]:
A .== A

2x2 BitArray{2}:
 true  true
 true  true

`*` performs matrix multiplication; `A\B` computes `inv(A)*B`:

In [35]:
A * A

2x2 Array{Int64,2}:
  7  10
 15  22

In [36]:
A \ A

2x2 Array{Float64,2}:
  1.0  0.0
 -0.0  1.0

## Strings

Julia uses double quotes for strings.

In [37]:
str = "my string"

"my string"

You can interpolate strings into other strings.

In [38]:
str = "the string was: $str"

"the string was: my string"

You can also interpolate entire expressions.

In [39]:
str = "the answer is $(6*7)"

"the answer is 42"

## Dicts

Julia has a dictionary structure somewhat like MATLAB's `struct`:

In [61]:
using Compat
@compat x = Dict("hello" => 1, "world" => 2)

Dict{ASCIIString,Int64} with 2 entries:
  "hello" => 1
  "world" => 2

(Dictionary syntax has changed between Julia 0.3 and 0.4. Here, I use `Compat` and the `@compat` macro to enable 0.4 syntax.)

In [41]:
x["hello"]

1

In [42]:
x["world"]

2

In [62]:
x["foo"] = 40
x

Dict{ASCIIString,Int64} with 3 entries:
  "hello" => 1
  "world" => 2
  "foo"   => 40

In [64]:
for (k, v) in x
    println("key: $k, value: $v")
end

key: hello, value: 1
key: world, value: 2
key: foo, value: 40


## Loops

In [44]:
factorial(20)

2432902008176640000

In [45]:
x = 1
for i = 1:20
    x *= i
end
x

2432902008176640000

In [46]:
x = 1
i = 1
while i <= 20
    x *= i
    i += 1
end
x

2432902008176640000

## Functions

In [65]:
v = rand(10^7)

function mydiff(v)
    out = zeros(length(v)-1)
    for i = 2:length(v)
        out[i-1] = v[i-1] - v[i]
    end
    out
end

mydiff(v)

9999999-element Array{Float64,1}:
 -0.570997  
  0.723773  
 -0.763809  
 -0.0416354 
 -0.0166646 
  0.301619  
  0.389968  
 -0.363454  
  0.399117  
 -0.650638  
  0.600531  
 -0.536499  
  0.0341981 
  ⋮         
 -0.00708545
 -0.50917   
  0.414576  
  0.194557  
 -0.128718  
 -0.709402  
  0.377192  
 -0.121027  
 -0.0346734 
  0.570987  
 -0.576143  
 -0.132823  

In [48]:
f(x) = x*5+1
f(5)

26

You can specify that functions take specific types. (This will become important later.) Type declarations are not necessary for performance.

In [49]:
g(x::Int) = x*5+1
g(5)

26

In [50]:
g(5.0)

LoadError: LoadError: MethodError: `g` has no method matching g(::Float64)
while loading In[50], in expression starting on line 1

Julia is fast because it can compile these functions down to assembly. Let's take a look:

In [51]:
@code_native mydiff(5)

	.section	__TEXT,__text,regular,pure_instructions
Filename: In[47]
Source line: 4
	pushq	%rbp
	movq	%rsp, %rbp
	pushq	%rbx
	subq	$40, %rsp
	movq	$4, -40(%rbp)
Source line: 4
	movabsq	$jl_pgcstack, %rbx
	movq	(%rbx), %rax
	movq	%rax, -32(%rbp)
	leaq	-40(%rbp), %rax
	movq	%rax, (%rbx)
	vxorps	%xmm0, %xmm0, %xmm0
	vmovups	%xmm0, -24(%rbp)
	movabsq	$4520928512, %rax       ## imm = 0x10D77E500
Source line: 4
	movq	(%rax), %rdi
	movabsq	$call, %rax
	movabsq	$4520883568, %rsi       ## imm = 0x10D773570
	xorl	%edx, %edx
	callq	*%rax
	movabsq	$13133343488, %rcx      ## imm = 0x30ECEEB00
	movq	%rax, -16(%rbp)
	movq	%rax, %rdi
	vxorps	%xmm0, %xmm0, %xmm0
	callq	*%rcx
	movq	%rax, -24(%rbp)
Source line: 8
	movq	-32(%rbp), %rcx
	movq	%rcx, (%rbx)
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	ret


In general, code that is not inside a function is not optimized, so always put performance-critical code in a function.

In [66]:
@time mydiff(v);

elapsed time: 0.10735991 seconds (76 MB allocated)


In [67]:
@time begin
    out = zeros(length(v)-1)
    for i = 2:length(v)
        out[i-1] = v[i-1] - v[i]
    end
end

elapsed time: 2.685195451 seconds (2365 MB allocated, 12.72% gc time in 105 pauses with 1 full sweep)


## Installing and Using Packages

There's a list of available Julia packages at [pkg.julialang.org](http://pkg.julialang.org/). You can install a package using:

In [ ]:
Pkg.add("Example")

and update all installed packages using:

In [ ]:
Pkg.update()

To load a package, use `using`:

In [69]:
using Example
hello("world") # This function comes from the Example package
names(Example)

3-element Array{Symbol,1}:
 :hello  
 :Example
 :domath 

## Reading and Writing Data

Julia can read and write arrays, strings, etc. to MAT files.

In [54]:
using MAT
X = [1, 2, 3, 4, 5]
matfile = matopen("mymat.mat", "w")
write(matfile, "X", X)
close(matfile)

In [55]:
matfile = matopen("mymat.mat")
read(matfile, "X")

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [56]:
close(matfile)

In [58]:
run(`/Applications/MATLAB_R2014b.app/bin/matlab -nodesktop -r "load mymat; disp(X); exit"`)


                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                   R2014b (8.4.0.150421) 64-bit (maci64)
                             September 15, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
                    1
                    2
                    3
                    4
                    5



You can also use the JLD package to read and write any Julia object.

In [59]:
using HDF5, JLD
@save "myjld.jld" X
X = nothing
@load "myjld.jld" X
X

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

The functions `readcsv` and `writecsv` (part of Julia) can be used to read and write CSV files. `readdlm` and `writedlm` support arbitrary delimiters.